//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_AccountCategory
    {
        public Acc_AccountCategory()
        {
            this.Acc_Accounts = new HashSet<Acc_Accounts>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName_Ara { get; set; }
        public string CategroyName_Eng { get; set; }
        public bool IsDisableCategory { get; set; }
    
        public virtual ICollection<Acc_Accounts> Acc_Accounts { get; set; }
    }
}
