//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_AccountReconcilation
    {
        public int AccountReconcileId { get; set; }
        public int YearId { get; set; }
        public string ReconcileAccountId { get; set; }
        public decimal ReconciledLastBalDebit { get; set; }
        public decimal ReconciledLastBalCredit { get; set; }
        public decimal ReconciledCurrentBalDebit { get; set; }
        public decimal ReconciledCurrentBalCredit { get; set; }
    
        public virtual Acc_Accounts Acc_Accounts { get; set; }
    }
}
