//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_CashierTrans
    {
        public int TransId { get; set; }
        public System.DateTime TransDate { get; set; }
        public string LocationId { get; set; }
        public string transRefNo { get; set; }
        public string VoucherNO { get; set; }
        public decimal MachineNo { get; set; }
        public string CashierName { get; set; }
        public decimal ZReadNO { get; set; }
        public System.DateTime CurrentZDate { get; set; }
        public Nullable<System.DateTime> LastZDate { get; set; }
        public decimal CashAmount { get; set; }
        public Nullable<decimal> LastCashAmount { get; set; }
        public decimal VisaAmount { get; set; }
        public Nullable<decimal> LastVisaAmount { get; set; }
        public decimal CurrentTotalZAmount { get; set; }
        public Nullable<decimal> LastTotalZAmount { get; set; }
        public decimal CurrentReturnsAmount { get; set; }
        public Nullable<decimal> LastReturnsAmount { get; set; }
        public decimal NetAmount { get; set; }
        public decimal CurrentGrandTotal { get; set; }
        public Nullable<decimal> LastGrandTotal { get; set; }
        public bool Icrease { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> UserDate { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Gnrl_Loctions Gnrl_Loctions { get; set; }
    }
}
