//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_VouchersType
    {
        public Acc_VouchersType()
        {
            this.Acc_Voucher = new HashSet<Acc_Voucher>();
        }
    
        public string VoucherTypeId { get; set; }
        public string VoucherName_Ara { get; set; }
        public string VoucherNmae_Eng { get; set; }
        public string CreditAccountid { get; set; }
        public Nullable<int> VoucherCurrancyid { get; set; }
        public string DetailExtraField1 { get; set; }
        public string DetailExtraField2 { get; set; }
        public string DetailExtraField3 { get; set; }
        public string DetailExtraField4 { get; set; }
        public string DetailExtraField5 { get; set; }
        public string MainExtraField1 { get; set; }
        public string MainExtraField2 { get; set; }
        public string MainExtraField3 { get; set; }
        public string MainExtraField4 { get; set; }
        public string MainExtraField5 { get; set; }
        public string DepitAccountId { get; set; }
        public string ShortName_Ara { get; set; }
        public string ShortName_Eng { get; set; }
        public Nullable<int> DtlValidationField1 { get; set; }
        public Nullable<int> DtlValidationField2 { get; set; }
        public Nullable<int> DtlValidationField3 { get; set; }
        public Nullable<int> DtlValidationField4 { get; set; }
        public Nullable<int> DtlValidationField5 { get; set; }
        public Nullable<int> MainValidationField1 { get; set; }
        public Nullable<int> MainValidationField2 { get; set; }
        public Nullable<int> mainValidationField3 { get; set; }
        public Nullable<int> MainValidationField4 { get; set; }
        public Nullable<int> MainValidationField5 { get; set; }
    
        public virtual Acc_Currancy Acc_Currancy { get; set; }
        public virtual Acc_Accounts Acc_Accounts { get; set; }
        public virtual ICollection<Acc_Voucher> Acc_Voucher { get; set; }
    }
}
