//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_Accounts
    {
        public string AccountID { get; set; }
        public string AccountName_Ar { get; set; }
        public string AccountName_Eng { get; set; }
        public int AccountTypeId { get; set; }
        public int AccountLevel { get; set; }
        public Nullable<int> AccountCategoryId { get; set; }
        public bool IsSubAccount { get; set; }
        public bool IsDisableAccount { get; set; }
        public string AccountRef1 { get; set; }
        public string AccountRef2 { get; set; }
        public string ParentId { get; set; }
        public string CurrancyId { get; set; }
        public string GroupAccount { get; set; }
    
        public virtual Acc_AccountCategory Acc_AccountCategory { get; set; }
        public virtual Acc_Accountype Acc_Accountype { get; set; }
    }
}
