//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_Reconcilation
    {
        public Acc_Reconcilation()
        {
            this.Acc_ReconcilationDtl = new HashSet<Acc_ReconcilationDtl>();
        }
    
        public string ReconcileId { get; set; }
        public string ReconcileAccountId { get; set; }
        public int ReconcileYear { get; set; }
        public decimal CurrentStatemantAmount { get; set; }
        public System.DateTime CurrentStatementDate { get; set; }
        public Nullable<decimal> ReconciledLastBal { get; set; }
        public Nullable<System.DateTime> ReconciledLastDate { get; set; }
        public Nullable<decimal> ReconcilationValue { get; set; }
        public decimal AccountBalance { get; set; }
        public Nullable<decimal> DiffreneceInBook { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> UserDate { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Acc_Accounts Acc_Accounts { get; set; }
        public virtual ICollection<Acc_ReconcilationDtl> Acc_ReconcilationDtl { get; set; }
    }
}
