//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_AccountBalances
    {
        public int BalanceId { get; set; }
        public int YearId { get; set; }
        public string AccountId { get; set; }
        public decimal OpenBalanceDr { get; set; }
        public decimal OpenBalanceCr { get; set; }
        public decimal DebitMonth01 { get; set; }
        public decimal CreditMonth01 { get; set; }
        public decimal DebitMonth02 { get; set; }
        public decimal CreditMonth02 { get; set; }
        public decimal DebitMonth03 { get; set; }
        public decimal CreditMonth03 { get; set; }
        public decimal DebitMonth04 { get; set; }
        public decimal CreditMonth04 { get; set; }
        public decimal DebitMonth05 { get; set; }
        public decimal CreditMonth05 { get; set; }
        public decimal DebitMonth06 { get; set; }
        public decimal CreditMonth06 { get; set; }
        public decimal DebitMonth07 { get; set; }
        public decimal CreditMonth07 { get; set; }
        public decimal DebitMonth08 { get; set; }
        public decimal CreditMonth08 { get; set; }
        public decimal DebitMonth09 { get; set; }
        public decimal CreditMonth09 { get; set; }
        public decimal DebitMonth10 { get; set; }
        public decimal CreditMonth10 { get; set; }
        public decimal DebitMonth11 { get; set; }
        public decimal CreditMonth11 { get; set; }
        public decimal DebitMonth12 { get; set; }
        public decimal CreditMonth12 { get; set; }
    
        public virtual Acc_Accounts Acc_Accounts { get; set; }
    }
}
