//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_CashierTransAccountSetting
    {
        public int CTId { get; set; }
        public string CTLocationId { get; set; }
        public Nullable<int> CTCostCenterId { get; set; }
        public string CTWarehouseId { get; set; }
        public string SalesAccountId { get; set; }
        public string VisaAccountId { get; set; }
        public string CashAmountId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> UserDate { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Acc_Accounts Acc_Accounts { get; set; }
        public virtual Acc_Accounts Acc_Accounts1 { get; set; }
        public virtual Acc_Accounts Acc_Accounts2 { get; set; }
    }
}
