//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_VoucherInvoiceDtl
    {
        public string VoucherTypeId { get; set; }
        public string voucherId { get; set; }
        public int YearId { get; set; }
        public int Line_no { get; set; }
        public int DetailId { get; set; }
        public bool IsPaid { get; set; }
        public string InvoiceNo { get; set; }
        public bool LockInvoice { get; set; }
        public string PayLocationId { get; set; }
        public string PayCostCenter { get; set; }
        public decimal InvoiceAmount { get; set; }
        public decimal PaidInvoiceAmount { get; set; }
    
        public virtual Acc_VoucherDtl Acc_VoucherDtl { get; set; }
    }
}
