//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_CostCenter
    {
        public Acc_CostCenter()
        {
            this.Acc_CostCenter1 = new HashSet<Acc_CostCenter>();
            this.Ast_Assets = new HashSet<Ast_Assets>();
        }
    
        public int CostCenterId { get; set; }
        public string CostCenterName_Ara { get; set; }
        public string CostCenterName_Eng { get; set; }
        public bool IsDisable { get; set; }
        public Nullable<decimal> CostOpenBalance { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<Acc_CostCenter> Acc_CostCenter1 { get; set; }
        public virtual Acc_CostCenter Acc_CostCenter2 { get; set; }
        public virtual ICollection<Ast_Assets> Ast_Assets { get; set; }
    }
}
