//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_Accountype
    {
        public int TypeID { get; set; }
        public string TypeName_Ara { get; set; }
        public string TypeName_Eng { get; set; }
        public bool IsDisable { get; set; }
    }
}
