//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_Budgets
    {
        public Acc_Budgets()
        {
            this.Acc_BudgetsDtl = new HashSet<Acc_BudgetsDtl>();
        }
    
        public int BudgetId { get; set; }
        public int BudgetYearId { get; set; }
        public string BudgetName_Ara { get; set; }
        public string BudgetName_Eng { get; set; }
        public bool IsDisable { get; set; }
    
        public virtual ICollection<Acc_BudgetsDtl> Acc_BudgetsDtl { get; set; }
    }
}
