//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ast_AssetAccountsSetting
    {
        public int Id { get; set; }
        public string AssetId { get; set; }
        public string AssetLocationId { get; set; }
        public string AssetCostCenterId { get; set; }
        public string AssetAccountId { get; set; }
        public string AccumolatedAccountId { get; set; }
        public string DepreciationAccountId { get; set; }
        public string AssetSaleProfitAccountId { get; set; }
        public string AssetSaleLossAccountId { get; set; }
        public string AssetRevaluteAccountId { get; set; }
        public string AssetCashAccountId { get; set; }
    
        public virtual Acc_Accounts Acc_Accounts { get; set; }
        public virtual Acc_Accounts Acc_Accounts1 { get; set; }
        public virtual Acc_Accounts Acc_Accounts2 { get; set; }
        public virtual Acc_Accounts Acc_Accounts3 { get; set; }
        public virtual Acc_Accounts Acc_Accounts4 { get; set; }
        public virtual Acc_Accounts Acc_Accounts5 { get; set; }
        public virtual Acc_Accounts Acc_Accounts6 { get; set; }
    }
}
