//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ast_AssetCatogry
    {
        public int AstCatId { get; set; }
        public string AstCatName_Ara { get; set; }
        public string AstCatName_Eng { get; set; }
        public bool IsDisable { get; set; }
    }
}
