//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ast_Assets
    {
        public Ast_Assets()
        {
            this.Asst_Transfers = new HashSet<Asst_Transfers>();
            this.Ast_DepreciationDtl = new HashSet<Ast_DepreciationDtl>();
            this.Ast_Revaluated = new HashSet<Ast_Revaluated>();
        }
    
        public string AssetId { get; set; }
        public string AssetRef { get; set; }
        public string AssetName_Ara { get; set; }
        public string AssetName_Eng { get; set; }
        public Nullable<int> AssetCategoryId { get; set; }
        public Nullable<int> AssetCostCenterId { get; set; }
        public Nullable<System.DateTime> AssetCostCenterDate { get; set; }
        public string CreditAccountId { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int Quantity { get; set; }
        public decimal InvoiceAmount { get; set; }
        public string AssetLocationId { get; set; }
        public string Currencyid { get; set; }
        public decimal CurrancyRate { get; set; }
        public int DepreciationMethodId { get; set; }
        public decimal DepreciationPrecentage { get; set; }
        public decimal AccumulativeDepreciationAmount { get; set; }
        public decimal LastDepreciationAmount { get; set; }
        public Nullable<System.DateTime> LastDepreciationDate { get; set; }
        public decimal AssetRevaluatedValue { get; set; }
        public decimal AssetBookValue { get; set; }
        public string AssetImage { get; set; }
        public string AssetBarcode { get; set; }
        public bool AssetDepreciatedCat { get; set; }
        public bool IsWriteOff { get; set; }
        public bool IsPost { get; set; }
    
        public virtual Acc_CostCenter Acc_CostCenter { get; set; }
        public virtual ICollection<Asst_Transfers> Asst_Transfers { get; set; }
        public virtual Ast_AssetCatogry Ast_AssetCatogry { get; set; }
        public virtual Gnrl_Loctions Gnrl_Loctions { get; set; }
        public virtual Ast_DepreciationMethod Ast_DepreciationMethod { get; set; }
        public virtual ICollection<Ast_DepreciationDtl> Ast_DepreciationDtl { get; set; }
        public virtual ICollection<Ast_Revaluated> Ast_Revaluated { get; set; }
    }
}
