//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gnrl_LocationType
    {
        public Gnrl_LocationType()
        {
            this.Gnrl_Loctions = new HashSet<Gnrl_Loctions>();
        }
    
        public int LoctionTypeId { get; set; }
        public string LocationTypeName_Ara { get; set; }
        public string LocationTypeName_Eng { get; set; }
    
        public virtual ICollection<Gnrl_Loctions> Gnrl_Loctions { get; set; }
    }
}
