//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gnrl_TableSequence
    {
        public string TableName { get; set; }
        public string UniqueYear { get; set; }
        public long CurrentValue { get; set; }
        public string LocationId { get; set; }
        public Nullable<short> SerialSize { get; set; }
    }
}
