//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gnrl_FinancialYear
    {
        public int YearId { get; set; }
        public string YearName { get; set; }
        public System.DateTime YearBegin { get; set; }
        public System.DateTime YearEnd { get; set; }
        public bool IsDefaultYear { get; set; }
        public bool IsClosedYear { get; set; }
        public int prefix { get; set; }
    }
}
