//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grnl_Audit
    {
        public Grnl_Audit()
        {
            this.Grnl_AuditDtl = new HashSet<Grnl_AuditDtl>();
        }
    
        public long AuditId { get; set; }
        public int AuditActionId { get; set; }
        public string TableName { get; set; }
        public int UserId { get; set; }
        public System.DateTime ActionDate { get; set; }
    
        public virtual ICollection<Grnl_AuditDtl> Grnl_AuditDtl { get; set; }
    }
}
