//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_FormFunctions
    {
        public int FunctionID { get; set; }
        public string FunctionText_Ara { get; set; }
        public string FunctionText_Eng { get; set; }
    }
}
