//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_Groups
    {
        public Sec_Groups()
        {
            this.Sec_GroupRights = new HashSet<Sec_GroupRights>();
            this.Sec_Users = new HashSet<Sec_Users>();
        }
    
        public string GroupID { get; set; }
        public string Name_Ara { get; set; }
        public string Name_Eng { get; set; }
        public bool IsDisable { get; set; }
    
        public virtual ICollection<Sec_GroupRights> Sec_GroupRights { get; set; }
        public virtual ICollection<Sec_Users> Sec_Users { get; set; }
    }
}
