//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_MainMenu
    {
        public Sec_MainMenu()
        {
            this.Sec_GroupRights = new HashSet<Sec_GroupRights>();
            this.Sec_MainMenu1 = new HashSet<Sec_MainMenu>();
        }
    
        public string MenuID { get; set; }
        public string Text_Ara { get; set; }
        public string Text_Eng { get; set; }
        public string ParentMenuID { get; set; }
        public string FormName { get; set; }
        public string FormOption { get; set; }
        public int FormAllowedFunctions { get; set; }
        public Nullable<bool> SplitBefore { get; set; }
        public Nullable<bool> ShowInMenuBar { get; set; }
        public Nullable<bool> ShowInToolBar { get; set; }
        public string ToolBarImage { get; set; }
        public Nullable<int> ToolBarIndex { get; set; }
        public string TooBarText_Ara { get; set; }
        public string TooBarText_Eng { get; set; }
    
        public virtual ICollection<Sec_GroupRights> Sec_GroupRights { get; set; }
        public virtual ICollection<Sec_MainMenu> Sec_MainMenu1 { get; set; }
        public virtual Sec_MainMenu Sec_MainMenu2 { get; set; }
    }
}
