//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_Users
    {
        public Sec_Users()
        {
            this.Sec_Groups = new HashSet<Sec_Groups>();
        }
    
        public int UserID { get; set; }
        public string UserLogin { get; set; }
        public string Name_Ara { get; set; }
        public string Name_Eng { get; set; }
        public string Password { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual ICollection<Sec_Groups> Sec_Groups { get; set; }
    }
}
