//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Srch_SearchMaster
    {
        public Srch_SearchMaster()
        {
            this.Srch_SearchParameters = new HashSet<Srch_SearchParameters>();
        }
    
        public int SearchID { get; set; }
        public string SearchSQL_Ara { get; set; }
        public string SearchSQL_Eng { get; set; }
        public string SearchResultStyle_Ara { get; set; }
        public string SearchResultStyle_Eng { get; set; }
        public bool AddWhere { get; set; }
        public int ParametersColumns { get; set; }
        public string ReturnsFields { get; set; }
        public string AddNewForm { get; set; }
        public string EditForm { get; set; }
    
        public virtual ICollection<Srch_SearchParameters> Srch_SearchParameters { get; set; }
    }
}
