//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Srch_SearchParameters
    {
        public int SearchID { get; set; }
        public int ParameterID { get; set; }
        public string ValuesKeys { get; set; }
        public string ConditionDataFields { get; set; }
        public string ConditionParameters { get; set; }
        public string ParameterText_Ara { get; set; }
        public string ParameterText_Eng { get; set; }
        public string ParameterControl { get; set; }
        public int ParameterControlWidth { get; set; }
        public string ComperOrders { get; set; }
        public string ComboBoxSQL_Ara { get; set; }
        public string ComboBoxSQL_Eng { get; set; }
        public string ComboBoxValueMembers { get; set; }
        public string ComboBoxDisplayMember_Ara { get; set; }
        public string ComboBoxDisplayMember_Eng { get; set; }
    
        public virtual Srch_SearchMaster Srch_SearchMaster { get; set; }
    }
}
